### ISSUE TITLE
Nap assumes everything in INSTALLED_APPS is a module

### ISSUE THREAD

**Issue by bobobo1618** [funkybob/django-nap#46]
As of 1.7, it's entirely normal to have a reference to an `AppConfig` class in `INSTALLED_APPS`.

Since nap tries to import everything in `INSTALLED_APPS` [during autodiscovery](https://github.com/funkybob/django-nap/blob/3ebe99c7e113c0c4aa8f5857e290394c4e2cc3f8/nap/rest/api.py#L80), attempting to run a Django app using these `AppConfig` classes results in ImportErrors.

I have a [commit written to address this](https://github.com/bobobo1618/django-nap/commit/ba099c9b914a3496e0d8fa28f591ee5fa02ef1f5) but I believe some kind of logging might be a better way to handle this.

**Comment by funkybob** [comment]
Can we consider this closed now?
