### ISSUE TITLE
0.14.1.1 update has broken NewRelic instrument wrapper

### ISSUE THREAD

**Issue by geeknam** [funkybob/django-nap#50]
NR is recording API calls against  `nap.rest.publisher:view`. The upgrade was from 0.13.6 straight to 0.14.1.1 (as part of Django 1.7 migration).

**Comment by funkybob** [comment]
did you update your newrelic config with the new version?

http://django-nap.readthedocs.org/en/latest/extras/newrelic.html

**Comment by geeknam** [comment]
Updating NR config worked. Thanks @funkybob !
