### ISSUE TITLE
ObjectPutMixin should use mapper._apply() instead of mapper._patch()

### ISSUE THREAD

**Issue by ianawilson** [funkybob/django-nap#52]
An HTTP PUT is a complete replacement of a resource, so I think it should use `mapper._apply()`, which expects all required fields to have values.

Additionally, there should probably be an `ObjectPatchMixin` for HTTP PATCH (with a `def patch(..)`) that uses `mapper._patch()` and behaves like the existing `ObjectPutMixin`.

I'll probably have time to make a PR for this, but wanted to hear if this implementation (`ObjectPutMixin` with HTTP PATCH behavior) was intentional or an oversight.

Lastly, I realize this is a backwards incompatible change, but it seems like a bug in its current implementation, since it doesn't match the HTTP spec:

- [HTTP PUT](https://tools.ietf.org/html/rfc7231#section-4.3.4)
- [HTTP PATCH](https://tools.ietf.org/html/rfc5789)

Thoughts?

**Comment by funkybob** [comment]
Makes sense to me.  PR is, of course, welcome.

I'd been focusing on lower levels of the interfaces more lately.

**Comment by ianawilson** [comment]
Great. I'll probably put together a PR this weekend.

**Comment by ianawilson** [comment]
PR for these suggestions: #53
