### ISSUE TITLE
Deleting successfully deletes instance but returns 500 (ObjectDeleteMixin)

### ISSUE THREAD

**Issue by limbera** [funkybob/django-nap#62]
When I issue a delete request to remove an instance, it is successfully deleted but the return code is 500. Looks like it's trying to get a field from the instance after it's been deleted? 

Mapper + Model + Traceback: http://dpaste.com/1VJMX4P

**Comment by funkybob** [comment]
Your delete view is trying to render the instance.

Your data mapper tries to find the first related Record:

    File "/Users/dre/code/gametraka_project/apps/events/mappers.py", line 48, in date
      return str(self.record_set.first().timestamp)

Any call to QuerySet.first() can yield None

So, either don't try to return the rendered instance, or [and this will protect more] make that line more like:

    value = self.record_set.first()
    return value.timestamp if value else None
