### ISSUE TITLE
default_app_config leads to ImportError

### ISSUE THREAD

**Issue by nkuttler** [funkybob/django-nap#72]
For some reason I had `'nap'` in my `INSTALLED_APPS` and got this really confusing `ImportError: No module named apps` on Django 1.8. Removing `default_app_config` from `nap/__init__.py` fixed this, as does removing nap from the installed apps.

I wonder if it's possible to provide a better error by default (probably Django's job), or to remove the app config. If not feel free to close this.

**Comment by funkybob** [comment]
Ah, yeah, wouldn't hurt to open a ticket on Django for that.

That was left over from when the old Publisher code had an auto-discover.

Fixed in 156c808
